from abc import ABC,abstractmethod
from typing import Any,Optional

class IRedisRepository(ABC):
    @abstractmethod
    def set(self,key: str,value: Any,ttl_seconds: Optional[int] = None) -> None:...
    @abstractmethod
    def get(self, key: str) -> Optional[Any]:...
    @abstractmethod
    def update(self, key: str, value: Any) -> bool:...
    @abstractmethod
    def renew_ttl(self, key: str, ttl_seconds: int) -> bool:...
    @abstractmethod
    def get_ttl(self, key: str) -> int:...
    @abstractmethod
    def delete(self, key: str) -> None:...